Dėl Seimo narių skaičiaus 141->121
Lietuvos-Respublika/Lietuvos-Respublikos-Konstitucija pull request #3
Opened 2019-05-09 17:15 UTC by Dalia-Grybauskaite

Lietuvos Respublikos Konstitucijos 55 straipsnio pakeitimo įstatymas

Priėmė: Piliečių referendumas
Šis įstatymas taikomas eiliniams ir pirmalaikiams Lietuvos Respublikos Seimo rinkimams, organizuojamiems po šio įstatymo įsigaliojimo

2019-05-09 17:15 UTC, Dalia-Grybauskaite commented
Šaltinis: https://www.e-tar.lt/portal/lt/legalAct/dae39d8030fd11e9b66f85227a03f7a3

2019-05-09 18:37 UTC, Daugilas requested changes
Jokios prasmės nematau šiam pakeitimui. Atrodo, kad dabartinė Seimo dauguma bando kažkur nukreipti dėmesį nuo rimtų dalykų.

2019-05-10 09:20 UTC, prSquirrel requested changes

2019-05-10 09:20 UTC, prSquirrel commented on 05 Seimas.md
> +Seimą sudaro Tautos atstovai – 121 Seimo narys, kurie renkami ketveriems metams remiantis visuotine, lygia, tiesiogine rinkimų teise ir slaptu balsavimu.
Neatrodo labai stabilus pakeitimas, bandykime pradžiai `140`.

2019-05-16 15:24 UTC, Dalia-Grybauskaite commented
rinkėjų sąrašuose įrašyta rinkėjų - 2486915,
referendume dalyvavo - 1188604 (47,79%)

Referendumas laikomas neįvykusiu.

https://www.vrk.lt/2019-prezidento/rezultatai?srcUrl=/rinkimai/904/1/1666/rezultatai/lt/rezultataiRefSavivaldybese.html

2019-05-16 15:24 UTC, closed without merging