Dėl pilietybės išsaugojimo
Lietuvos-Respublika/Lietuvos-Respublikos-Konstitucija pull request #5
Opened 2024-05-10 14:16 UTC by LR-Seimas

Lietuvos Respublikos Seimas nutarė 2024 m. gegužės 12 d. paskelbti privalomąjį referendumą dėl Lietuvos Respublikos Konstitucijos 12 straipsnio pakeitimo.

Pateikti privalomajam referendumui šį įstatymo projekto tekstą.

Priėmė: Lietuvos Respublikos Seimas
Įstatymo projektas sukurtas: 2023-05-23
Referendumo data: 2024-05-12
Paskelbta: TAR, 2023-05-23, Nr. 9708

2024-05-10 14:30 UTC, Daugilas approved these changes

2024-05-10 14:31 UTC, Daugilas approved these changes

2024-05-10 14:31 UTC, Daugilas approved these changes

2024-05-10 14:33 UTC, MatasAdmoneo commented on 01 Lietuvos valstybė.md
> +Konstitucinis įstatymas taip pat nustato Lietuvos Respublikos pilietybės netekimo pagrindus ir tvarką.
LGTM

2024-05-10 15:01 UTC, vstraigis approved these changes

2024-05-10 15:07 UTC, Tomas-Git approved these changes
LGTM

2024-05-10 15:14 UTC, benmandr approved these changes

2024-05-10 15:24 UTC, Didainius commented
Needs UX improvements

2024-05-10 15:47 UTC, rytisder approved these changes

2024-05-10 16:32 UTC, GABRAH approved these changes
px sueis

2024-05-10 17:36 UTC, PetrasJ approved these changes

2024-05-10 17:42 UTC, Spragalas approved these changes

2024-05-10 18:19 UTC, egleged approved these changes

2024-05-10 18:23 UTC, aivarasbaranauskas approved these changes

2024-05-10 19:36 UTC, eliteaz approved these changes

2024-05-10 19:41 UTC, EdvinasBa approved these changes

2024-05-10 19:52 UTC, domnantas approved these changes

2024-05-11 07:44 UTC, ton31337 approved these changes

2024-05-11 08:00 UTC, Visagalis approved these changes

2024-05-11 08:27 UTC, justasam approved these changes
lgtm

2024-05-11 08:59 UTC, pDonatas approved these changes
LGTM

2024-05-11 09:09 UTC, martynasali approved these changes

2024-05-11 09:37 UTC, AzisK approved these changes

2024-05-12 14:00 UTC, RimvydasPet approved these changes

2024-05-12 15:21 UTC, Mantux11 approved these changes
👍

2024-05-12 15:41 UTC, holmraven approved these changes

2024-05-12 15:59 UTC, ovistr approved these changes

2024-05-12 16:42 UTC, sakalauskas03 approved these changes

2024-05-12 16:47 UTC, acirtautas approved these changes

2024-05-13 05:27 UTC, karolis-p approved these changes

2024-05-13 05:41 UTC, herkusas approved these changes

2024-05-13 05:51 UTC, Nilsas approved these changes

2024-05-13 06:11 UTC, erikastr approved these changes

2024-05-13 06:22 UTC, KNartautas approved these changes

2024-05-13 06:27 UTC, julita-dargyte approved these changes

2024-05-13 06:33 UTC, arnaskro approved these changes

2024-05-13 06:45 UTC, pauleks approved these changes

2024-05-13 07:29 UTC, kristupasp approved these changes

2024-05-13 07:59 UTC, domnantas commented
nepraeina CI, closinam :(

2024-05-13 08:13 UTC, Didainius requested changes
Failed due to bad UX. Please improve documentation for next attempt.

2024-05-13 08:48 UTC, TadasVasiliauskas approved these changes

2024-05-13 09:48 UTC, vstraigis requested changes
CI/CD failing

2024-05-13 11:15 UTC, Gitanas-Nauseda commented
Referendumas laikomas įvykusiu.
Referendumo klausimas **nepriimtas**.

rinkėjų sąrašuose įrašyta rinkėjų - 2 396 990,
referendume dalyvavo - 1 413 288 (58,96%)

proc. balsai nuo galiojančių biuletenių
TAIP - 74,13% (1 026 408)
NE - 25,87% (358 113)
Negaliojančių biuletenių - 2,04% (28 767)

proc. balsai nuo rinkėjų skaičiaus:
TAIP - **42.82%**

Kad klausimas būtų priimtas, reikia surinkti daugiau nei 50% TAIP nuo visų rinkėjų.
Referendumo klausimo priėmimui pritrūko TAIP balsų: 172 088 (7,18% rinkėjų).


Šaltinis: https://rezultatai.vrk.lt/?srcUrl=/rinkimai/1504/1/2104/rezultatai/lt/rezultataiRefSavivaldybese.html

2024-05-13 11:15 UTC, closed without merging